export const products = [
  {
    id: 1,
    title: "Basic",
    price: "49$",
    usage: "Personal Use",
    num_of_projects: "3 projects",
    space: "1 GB disk",
    domain: "Custom domain",
    support: "24/5 support",
    icon: "plug",
    popular: false,
  },
  {
    id: 2,
    title: "Advanced",
    price: "99$",
    usage: "Personal Use",
    num_of_projects: "5 projects",
    space: "5 GB disk",
    domain: "Custom domain",
    support: "24/5 support",
    icon: "cog",
    popular: false,
  },
  {
    id: 3,
    title: "Professional",
    price: "149$",
    usage: "Personal Use",
    num_of_projects: "20 projects",
    space: "20 GB disk",
    domain: "Custom domain",
    support: "24/5 support",
    icon: "star",
    popular: true,
  },
  {
    id: 4,
    title: "Ultimate",
    price: "199$",
    usage: "Multi Use",
    num_of_projects: "Unlimited projects",
    space: "99 GB disk",
    domain: "Custom domain",
    support: "24/5 support",
    icon: "plus",
    popular: false,
  },
];
