export const products = [
  {
    id: 1,
    title: "Basic",
    price: "49$",
    usage: "Prices.personal_use",
    num_of_projects: "3",
    space: "1 GB",
    domain: "Custom domain",
    support: "24/5",
    icon: "plug",
    popular: false,
  },
  {
    id: 2,
    title: "Advanced",
    price: "99$",
    usage: "Prices.personal_use",
    num_of_projects: "5",
    space: "5 GB",
    domain: "Custom domain",
    support: "24/5",
    icon: "cog",
    popular: false,
  },
  {
    id: 3,
    title: "Professional",
    price: "149$",
    usage: "Prices.personal_use",
    num_of_projects: "20",
    space: "20 GB",
    domain: "Custom domain",
    support: "24/5",
    icon: "star",
    popular: true,
  },
  {
    id: 4,
    title: "Ultimate",
    price: "199$",
    usage: "Prices.multi_use",
    num_of_projects: "Prices.unlimited",
    space: "99 GB",
    domain: "Prices.custom_domain",
    support: "24/5",
    icon: "plus",
    popular: false,
  },
];
